services:
  mongo:
    image: mongo:7.0
    container_name: mongo-container

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

  server:
    image: dulajhashmika/server-dev:1.4.0
    container_name: server-container

    build:
      context: ./server
      dockerfile: Dockerfile

    ports:
      - "5000:5000"

    depends_on:
      - mongo

    volumes:
      - ./server:/app
      - /app/node_modules

    environment:
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}

  client:
    image: dulajhashmika/client-dev:1.5.0
    container_name: client-container

    build:
      context: ./client
      dockerfile: Dockerfile

    ports:
      - "5173:5173"

    depends_on:
      - server

    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_API_PROXY_TARGET: ${VITE_API_PROXY_TARGET:-http://server:5000}


volumes:
  mongo-data: